server:
  port: 8080
spring:
  datasource:
    username: root
    password: ranbaike@NB$N330
    url: jdbc:mysql://182.92.83.155:3306/android_data?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: SangZY
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
logging:
  config: classpath:log4j-spring.xml